### ISSUE TITLE
[meta] Add descriptors to existing integrations

### ISSUE THREAD

**Issue by rytilahti** [rytilahti/python-miio#1617]
This issue tracks the progress of adding descriptors to existing integrations.

## Call for help
If you possess any devices besides the 1st gen Roborock vacuum and a zhimi powerstrip which I have, please consider creating a pull request to add the `@sensor`, `@setting` and `@action` descriptor decorators so that homeassistant (and other potential downstreams) can create entities for your device automatically in the future. https://python-miio.readthedocs.io/en/latest/contributing.html#status-containers contains some documentation on the topic, and the issues linked below in the checklist show an example of how they look like in homeassistant.

The homeassistant fork at https://github.com/rytilahti/home-assistant/tree/xiaomi_miio/feat/entities_from_upstream allows testing your changes. When we get feature parity (or close to it) with the existing homeassistant support, the plan is to create smaller PRs (per platform, most likely) based on the fork to first enable the additional entities, and sunset the hard-coded ones afterward.

When adding the descriptors to the status classes, you can provide the following extra kwargs that are currently used by the fork:
* `device_class` would be great to have besides the name and the unit
* `icon` for defining custom icons when no `device_class` is set
*  `state_class` is not a priority at the moment, the default value should be chosen inside homeassistant and overridden only when needed

## Integrations

* [ ] airconditioner_miot.AirConditionerMiot
* [ ] airconditioningcompanion.AirConditioningCompanion
* [ ] airconditioningcompanion.AirConditioningCompanionV3
* [ ] airconditioningcompanionMCN.AirConditioningCompanionMcn02
* [ ] airdehumidifier.AirDehumidifier
* [ ] airqualitymonitor.AirQualityMonitor
* [ ] airqualitymonitor_miot.AirQualityMonitorCGDN1
* [ ] aqaracamera.AqaraCamera
* [ ] chuangmi_camera.ChuangmiCamera
* [ ] chuangmi_ir.ChuangmiIr
* [ ] chuangmi_plug.ChuangmiPlug
* [ ] cooker.Cooker
* [ ] curtain_youpin.CurtainMiot
* [ ] gateway.gateway.Gateway
* [ ] heater.Heater
* [ ] heater_miot.HeaterMiot
* [ ] huizuo.Huizuo
* [ ] huizuo.HuizuoLampFan
* [ ] huizuo.HuizuoLampHeater
* [ ] huizuo.HuizuoLampScene
* [ ] integrations.airpurifier.airdog.airpurifier_airdog.AirDogX3
* [ ] integrations.airpurifier.dmaker.airfresh_t2017.AirFreshA1
* [ ] integrations.airpurifier.dmaker.airfresh_t2017.AirFreshT2017
* [ ] integrations.airpurifier.zhimi.airfresh.AirFresh
* [ ] integrations.airpurifier.zhimi.airpurifier.AirPurifier
* [ ] integrations.airpurifier.zhimi.airpurifier_miot.AirPurifierMiot
* [ ] integrations.fan.dmaker.fan.FanP5
* [ ] integrations.fan.dmaker.fan_miot.FanMiot
* [ ] integrations.fan.dmaker.fan_miot.Fan1C
* [ ] integrations.fan.leshow.fan_leshow.FanLeshow
* [ ] integrations.fan.zhimi.fan.Fan
* [ ] integrations.fan.zhimi.zhimi_miot.FanZA5
* [ ] integrations.genericmiot.genericmiot.GenericMiot
* [ ] integrations.humidifier.deerma.airhumidifier_jsqs.AirHumidifierJsqs
* [ ] integrations.humidifier.deerma.airhumidifier_mjjsq.AirHumidifierMjjsq
* [ ] integrations.humidifier.shuii.airhumidifier_jsq.AirHumidifierJsq
* [ ] integrations.humidifier.zhimi.airhumidifier.AirHumidifier
* [ ] integrations.humidifier.zhimi.airhumidifier_miot.AirHumidifierMiot
* [ ] integrations.light.philips.ceil.Ceil
* [ ] integrations.light.philips.philips_bulb.PhilipsWhiteBulb
* [ ] integrations.light.philips.philips_bulb.PhilipsBulb
* [ ] integrations.light.philips.philips_eyecare.PhilipsEyecare
* [ ] integrations.light.philips.philips_moonlight.PhilipsMoonlight
* [ ] integrations.light.philips.philips_rwread.PhilipsRwread
* [ ] integrations.light.yeelight.yeelight.Yeelight
* [ ] integrations.petwaterdispenser.device.PetWaterDispenser
* [ ] integrations.vacuum.dreame.dreamevacuum_miot.DreameVacuum
* [ ] integrations.vacuum.mijia.g1vacuum.G1Vacuum
* [ ] integrations.vacuum.mijia.pro2vacuum.Pro2Vacuum
* [ ] integrations.vacuum.roborock.vacuum.RoborockVacuum
* [ ] integrations.vacuum.roidmi.roidmivacuum_miot.RoidmiVacuumMiot
* [ ] integrations.vacuum.viomi.viomivacuum.ViomiVacuum
* [ ] integrations.viomidishwasher.viomidishwasher.ViomiDishwasher
* [ ] powerstrip.PowerStrip
* [ ] pwzn_relay.PwznRelay
* [ ] scishare_coffeemaker.ScishareCoffee
* [ ] toiletlid.Toiletlid
* [ ] walkingpad.Walkingpad
* [ ] waterpurifier.WaterPurifier
* [ ] waterpurifier_yunmi.WaterPurifierYunmi
* [ ] wifirepeater.WifiRepeater
* [ ] wifispeaker.WifiSpeaker
* [ ] yeelight_dual_switch.YeelightDualControlModule
* [ ] alarmclock.AlarmClock
